### ISSUE TITLE
Fixes on account register

### ISSUE THREAD

**Issue by atoo** [BuildForSDGCohort2/Team-004-Backend#22]
Please provide the following fixes on POST users/register

1 for consistency, use json format for request input instead of form url encoded data
{
  "name": "name",
  "email": "email",
  "password": "password",
  "role": "role"
}

2 the accepted value for role should either be "student" or "teacher", in lowercase. No other value shoud be accepted

3 on success, don't return a string, but a json object with the user id and token
{
  "id": "user id",
  "token": "user token"
}

**Comment by jeancheikh** [comment]
1 When I use a json object it works fine for me.
2 The frontend should put in place validation to take care of this 
3 OK I made the correction

**Comment by atoo** [comment]
1 Don't say it is working for you, say you fixed. Otherwise why did you suggest me to use form url encode format when I got 404 error?
2 The backend should NEVER trust the frontend. you HAVE to validate and sanitize every input you receive. So please validate the input as I requested.

**Comment by jeancheikh** [comment]
Can you check?

**Comment by jeancheikh** [comment]
I made the requested corrections.
We are using express that by default do the heavy lifting. So I don't understand the issues you have when you send a json object. I did it and it works. That is how I tested.

**Comment by atoo** [comment]
Thank you
