### ISSUE TITLE
Fixes on account login

### ISSUE THREAD

**Issue by atoo** [BuildForSDGCohort2/Team-004-Backend#23]
Please provide the following fixes on POST users/login

1 for consistency, use json format for request input instead of form url encoded data
{
  "email": "email",
  "password": "password"
}

2 on success, don't return a string, but a json object with the user id, role and token
{
  "id": "user id",
  "role": "user role",
  "token": "user token"
}

**Comment by jeancheikh** [comment]
Corrected

**Comment by atoo** [comment]
Point 2 had not been fixed, still getting a string as output. I'm expecting a json object with 3 fields.

**Comment by jeancheikh** [comment]
Done

**Comment by atoo** [comment]
Thank you.
